# Generated by Django 5.0.2 on 2024-03-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_customer_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='user',
        ),
    ]
