# Generated by Django 5.0.2 on 2024-03-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_customer_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='user',
            new_name='customer',
        ),
    ]
